before:
  hooks:
    - go mod download
builds:
  - id: "operator-sdk"
    main: ./cmd/operator-sdk
    binary: operator-sdk
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - PWD=$(pwd)
    asmflags:
      - all=-trimpath={{ dir .Env.PWD }}
    gcflags:
      - all=-trimpath={{ dir .Env.PWD }}
    ldflags:
      - -X github.com/operator-framework/operator-sdk/internal/version.Version={{ .Version }}
      - -X github.com/operator-framework/operator-sdk/internal/version.GitVersion={{ .Version }}
      - -X github.com/operator-framework/operator-sdk/internal/version.GitCommit={{ .Commit }}
      - -X github.com/operator-framework/operator-sdk/internal/version.KubernetesVersion={{ .Env.K8S_VERSION }}
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    goos:
      - linux
      - darwin
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x

  # ansible-operator build steps
  - id: "ansible-operator"
    main: ./cmd/ansible-operator
    binary: ansible-operator
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - PWD=$(pwd)
    asmflags:
      - all=-trimpath={{ dir .Env.PWD }}
    gcflags:
      - all=-trimpath={{ dir .Env.PWD }}
    ldflags:
      - -X github.com/operator-framework/operator-sdk/internal/version.Version={{ .Version }}
      - -X github.com/operator-framework/operator-sdk/internal/version.GitVersion={{ .Version }}
      - -X github.com/operator-framework/operator-sdk/internal/version.GitCommit={{ .Commit }}
      - -X github.com/operator-framework/operator-sdk/internal/version.KubernetesVersion={{ .Env.K8S_VERSION }}
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    goos:
      - linux
      - darwin
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x

  # helm-operator build steps
  - id: "helm-operator"
    main: ./cmd/helm-operator
    binary: helm-operator
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - PWD=$(pwd)
    asmflags:
      - all=-trimpath={{ dir .Env.PWD }}
    gcflags:
      - all=-trimpath={{ dir .Env.PWD }}
    ldflags:
      - -X github.com/operator-framework/operator-sdk/internal/version.Version={{ .Version }}
      - -X github.com/operator-framework/operator-sdk/internal/version.GitVersion={{ .Version }}
      - -X github.com/operator-framework/operator-sdk/internal/version.GitCommit={{ .Commit }}
      - -X github.com/operator-framework/operator-sdk/internal/version.KubernetesVersion={{ .Env.K8S_VERSION }}
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    goos:
      - linux
      - darwin
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x

# We don't use archives, so skip creating them.
archives:
  - format: binary

checksum:
  name_template: 'checksums.txt'

# Sign checksum files with the local default PGP key.
signs:
  - signature: "${artifact}.asc"
    cmd: gpg2
    artifacts: checksum

# We use a custom changelog generator.
changelog:
  skip: true

# TODO(estroz): configure homebrew publishing
# brews:
#   - name: operator-sdk
#     ids:
#     - operator-sdk

# Close the Github milestone after the release completes.
milestones:
  - close: true
