before:
  hooks:
    - go version | grep --quiet "go1\.15\.2" || echo "Go binary version must be 1.15.2"
    - go mod download
builds:
  - id: operator-sdk
    main: ./cmd/operator-sdk
    binary: operator-sdk
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - REPO=github.com/operator-framework/operator-sdk
    mod_timestamp: "{{ .CommitTimestamp }}"
    asmflags:
      - all=-trimpath={{ dir .ArtifactPath | dir | dir | dir }}
    gcflags:
      - all=-trimpath={{ dir .ArtifactPath | dir | dir | dir }}
    ldflags:
      - -X {{ .Env.REPO }}/internal/version.Version={{ if not .IsSnapshot }}v{{ end }}{{ .Version }}
      - -X {{ .Env.REPO }}/internal/version.GitCommit={{ .FullCommit }}
      - -X {{ .Env.REPO }}/internal/version.KubernetesVersion={{ .Env.K8S_VERSION }}
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    goos:
      - linux
      - darwin
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x

  # ansible-operator build steps
  - id: ansible-operator
    main: ./cmd/ansible-operator
    binary: ansible-operator
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - REPO=github.com/operator-framework/operator-sdk
    mod_timestamp: "{{ .CommitTimestamp }}"
    asmflags:
      - all=-trimpath={{ dir .ArtifactPath | dir | dir | dir }}
    gcflags:
      - all=-trimpath={{ dir .ArtifactPath | dir | dir | dir }}
    ldflags:
      - -X {{ .Env.REPO }}/internal/version.Version={{ if not .IsSnapshot }}v{{ end }}{{ .Version }}
      - -X {{ .Env.REPO }}/internal/version.GitCommit={{ .FullCommit }}
      - -X {{ .Env.REPO }}/internal/version.KubernetesVersion={{ .Env.K8S_VERSION }}
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    goos:
      - linux
      - darwin
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x

  # helm-operator build steps
  - id: helm-operator
    main: ./cmd/helm-operator
    binary: helm-operator
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - REPO=github.com/operator-framework/operator-sdk
    mod_timestamp: "{{ .CommitTimestamp }}"
    asmflags:
      - all=-trimpath={{ dir .ArtifactPath | dir | dir | dir }}
    gcflags:
      - all=-trimpath={{ dir .ArtifactPath | dir | dir | dir }}
    ldflags:
      - -X {{ .Env.REPO }}/internal/version.Version={{ if not .IsSnapshot }}v{{ end }}{{ .Version }}
      - -X {{ .Env.REPO }}/internal/version.GitCommit={{ .FullCommit }}
      - -X {{ .Env.REPO }}/internal/version.KubernetesVersion={{ .Env.K8S_VERSION }}
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    goos:
      - linux
      - darwin
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x

# Use most recent tag and short commit for snapshot version.
snapshot:
  name_template: "{{ .Tag }}"

# We don't use archives, so skip creating them.
archives:
  - format: binary

checksum:
  name_template: 'checksums.txt'

# Sign checksum files with the local default PGP key.
# TODO(estroz): configure CI PGP key
# signs:
#   - signature: "${artifact}.asc"
#     cmd: gpg2
#     artifacts: checksum

# We use a custom changelog generator.
changelog:
  skip: true

# TODO(estroz): configure homebrew publishing
# brews:
#   - name: operator-sdk
#     ids:
#     - operator-sdk
